"""
Small Language Model (SLM) logic module for GeoAegis-ID.

This module integrates with a local Ollama service running Small Language Models
(such as qwen2.5:0.5b) to generate automated security incident summaries for anomalous user activities.
"""

from typing import Any, Dict
import requests


def generate_threat_summary(
    anomaly_data: Dict[str, Any],
    ollama_url: str = "http://localhost:11434"
) -> str:
    """
    Generates a concise 2-sentence security incident summary for an impossible travel alert
    using a local Ollama model (qwen2.5:0.5b).

    Why stream=False is used:
    Setting `stream=False` forces Ollama to evaluate the complete completion before returning a single,
    fully populated JSON response payload. This simplifies response parsing, avoids complex chunked stream
    processing overhead, and ensures the caller receives an atomic summary string ready for downstream consumption.

    Why a 5-second connection timeout is used:
    A strict `timeout=5` prevents blocking network socket connections if the local Ollama service is offline,
    unresponsive, slow, or experiencing heavy load. In security monitoring applications, blocking thread execution
    can degrade system availability. A hard timeout guarantees predictable latency bounds, falling back to a safe
    default threat summary string when the SLM is unavailable.

    Parameters:
        anomaly_data (dict): Dictionary containing anomaly telemetry (e.g., user_id, prev_login, curr_login, speed_kmh).
        ollama_url (str): Base URL for the local Ollama API instance (default: 'http://localhost:11434').

    Returns:
        str: A 2-sentence security summary generated by the SLM, or a fallback summary string upon error.
    """
    endpoint = f"{ollama_url.rstrip('/')}/api/generate"

    user_id = anomaly_data.get("user_id", "Unknown User")
    prev_loc = anomaly_data.get("prev_location", anomaly_data.get("prev_login", {}))
    curr_loc = anomaly_data.get("curr_location", anomaly_data.get("curr_login", {}))
    speed = anomaly_data.get("speed_kmh", anomaly_data.get("speed", "N/A"))

    prompt = (
        "You are an expert cybersecurity threat analyst. "
        "Summarize the following impossible travel security alert in exactly two concise sentences. "
        f"Alert Details: User {user_id} logged in from {prev_loc} and shortly after from {curr_loc} "
        f"at an calculated travel speed of {speed} km/h.\n"
        "Summary:"
    )

    payload = {
        "model": "qwen2.5:0.5b",
        "prompt": prompt,
        "stream": False,
    }

    try:
        response = requests.post(endpoint, json=payload, timeout=5)
        response.raise_for_status()
        data = response.json()
        summary = data.get("response", "").strip()

        if summary:
            return summary
        return (
            f"CRITICAL SECURITY ALERT: Impossible travel anomaly detected for user {user_id}. "
            f"Calculated speed of {speed} km/h between consecutive logins."
        )

    except requests.RequestException as exc:
        return (
            f"SECURITY ALERT: Impossible travel anomaly detected for user {user_id}. "
            f"Automated SLM threat summary unavailable (Ollama service offline or connection timeout)."
        )
